services:
  postgres:
    container_name: postgres-sql-ol
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2004
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: online_library
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-ol
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  ol-api:
    container_name: ol-api
    image: ol/ol:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
