spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_library
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOST_NAME}
    port: ${EMAIL_PORT_NUMBER}
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    security:
      jwt:
        secret-key: secret-key
        expiration: 86400000
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account
    cors:
      origins: http://localhost:4200,http://localhost:8080
    file:
      uploads:
        photos-output-path: ./uploads
server:
  port: 8088
