spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_library
    username: postgres
    password: 2004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOST_NAME}
    port: 587
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    security:
      jwt:
        secret-key: 9B4555CEB62AD8F6430091057409A1CBE7BA97FBCFCBFB18BA75413EDC22854B
        expiration: 86400000
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account
    cors:
      origins: http://localhost:4200,http://localhost:8080
    file:
      uploads:
        photos-output-path: ./uploads
server:
  port: 8088